name: CI

on: [push, pull_request]
permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
jobs:
  report-diff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get PR Diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --numstat origin/${{ github.base_ref }} > diff.txt
          TOTAL_LINES=$(awk '{ added += $1; removed += $2 } END { print added+removed }' diff.txt)
          echo "total-lines=$TOTAL_LINES" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const totalLines = ${{ steps.diff.outputs.total-lines }};
            const warning = `> [!WARNING]\n> The code changes are nearly 400 lines. Reviewers, please review carefully.\n> Reviewees, try to keep changes under 300 lines.`;
            const caution =`> [!CAUTION]\n> The code changes exceed 400 lines. This amount of changes may increase the risk of bugs.\n> Reviewees might find it easier to review if the pull request is split.`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Total Lines Changed:** ${totalLines}
              ${totalLines > 400 ? caution : totalLines > 300 ? warning:""}
              `
            });
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install modules
        uses: ./.github/actions/module-ci

  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Cached Dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Lint
        run: npm run lint

  test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Cached Dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Test
        run: npm run test:unit
  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install modules
        uses: ./.github/actions/cache-build

  bundle-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Cached Build
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: install modules
        uses: ./.github/actions/cache-build

      - name: Analyze bundle
        run: npx -p nextjs-bundle-analysis report

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: .next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v3
        if: success() && github.event.number
        with:
          workflow: ci.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: .next/analyze/base
          repo: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: bundle

      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare
      - name: Comment to Pull Request
        uses: ./.github/actions/pull-request-comment
        with:
          includes-comment: '<!-- __NEXTJS_BUNDLE -->'
          comment-body: $(cat .next/analyze/__bundle_analysis_comment.txt)

  lighthouse:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Cached Build
        uses: actions/cache@v4
        with:
          path: '**/.next'
          key: ${{ runner.os }}-npm-build-${{ github.sha }}

      - name: Use Cached Dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Run Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./lighthouserc.json
      - name: Create Lighthouse Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const results = ${{steps.lighthouse.outputs.manifest}}
            const table = `
              | URL | Performance | Accessibility | Best Practices | SEO | PWA |
              | --- | ----------- | ------------- | -------------- | --- | --- |
              ${results.map(result => `| ${result.url} | ${result.summary.performance * 100} | ${result.summary.accessibility * 100} | ${result.summary['best-practices']* 100} | ${result.summary.seo* 100} | ${result.summary.pwa* 100} |`).join('\n')}
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: table
            });
